#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jupyter_console
Version  : 5.0.0
Release  : 1
URL      : https://pypi.python.org/packages/05/d6/64a59934c7fb8bf46e8b42bf6b21015643d9dd02e52234c7c8bc929dec5e/jupyter_console-5.0.0.tar.gz
Source0  : https://pypi.python.org/packages/05/d6/64a59934c7fb8bf46e8b42bf6b21015643d9dd02e52234c7c8bc929dec5e/jupyter_console-5.0.0.tar.gz
Summary  : Jupyter terminal console
Group    : Development/Tools
License  : BSD-3-Clause-Clear
Requires: jupyter_console-bin
Requires: jupyter_console-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
# Jupyter Console
[![Build Status](https://travis-ci.org/jupyter/jupyter_console.svg?branch=master)](https://travis-ci.org/jupyter/jupyter_console)
[![Documentation Status](http://readthedocs.org/projects/jupyter-console/badge/?version=latest)](http://jupyter-console.readthedocs.org/en/latest/?badge=latest)

%package bin
Summary: bin components for the jupyter_console package.
Group: Binaries

%description bin
bin components for the jupyter_console package.


%package python
Summary: python components for the jupyter_console package.
Group: Default

%description python
python components for the jupyter_console package.


%prep
%setup -q -n jupyter_console-5.0.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1485736910
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1485736910
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jupyter-console

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
